POST http://localhost:5266/produtos
Content-Type: application/json

{
    "nome": "Headset",
    "quantidade": 20,
    "preco": 180.00
}

###

PUT http://localhost:5266/produtos/2
Content-Type: application/json

{
    "nome": "Mouse Gamer",
    "quantidade": 40,
    "preco": 199.90
}